interface Props {
  insights: string[];
  loading?: boolean;
}

export function InsightsPanel({ insights, loading }: Props) {
  if (loading) {
    return (
      <div className="bg-white rounded-lg border border-gray-200 p-4">
        <h3 className="text-sm font-semibold text-gray-900 mb-3">Insights</h3>
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-4 bg-gray-100 rounded animate-pulse" />
          ))}
        </div>
      </div>
    );
  }

  if (insights.length === 0) {
    return (
      <div className="bg-white rounded-lg border border-gray-200 p-4">
        <h3 className="text-sm font-semibold text-gray-900 mb-1">Insights</h3>
        <p className="text-sm text-gray-400">Upload financial data to generate insights.</p>
      </div>
    );
  }

  return (
    <div className="rounded-lg border border-[#E07A3E]/25 border-l-4 border-l-[#E07A3E] bg-[#fdf2e9]/40 p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-semibold text-gray-900">Insights & Priorities</h3>
        <span className="text-xs text-gray-400">Generated by Claude AI · {insights.length} observations</span>
      </div>
      <ul className="space-y-2.5">
        {insights.map((insight, i) => (
          <li key={i} className="flex items-start gap-2.5 text-sm text-gray-700 leading-relaxed">
            <span className="mt-2 flex-shrink-0 w-1.5 h-1.5 rounded-full bg-[#E07A3E]" />
            {insight}
          </li>
        ))}
      </ul>
    </div>
  );
}
